### ISSUE TITLE
Documentation for v3

### ISSUE THREAD

**Issue by peterch405** [smithlabcode/preseqR#20]
The instructions you published in you paper are great, (https://static-content.springer.com/esm/art%3A10.1007%2Fs40484-015-0049-7/MediaObjects/40484_2015_49_MOESM1_ESM.pdf) but they no longer work with the new version. Do you have an update vignette? Thank you.

**Comment by andrewdavidsmith** [comment]
Hi Peter. Please contact the authors directly about this via email -- we will be happy to hear from you in general. And in this specific case, you will hear from us soon in response to this query.

**Comment by peterch405** [comment]
Thank you. I look forward to hearing from you.

**Comment by chaodengusc** [comment]
Hi Peter,

Thanks for your interest in preseqR. I am preparing to update the vignette.
Now right I am collecting information from people for things like what
functions they often use and what features are important and so on. Would
you mind to leave me an email address in private so I can know your needs?

Best,

Chao



On Thu, Jul 27, 2017 at 10:03 AM, Peter Chovanec <notifications@github.com>
wrote:

> Thank you. I look forward to hearing from you.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_smithlabcode_preseqR_issues_20-23issuecomment-2D318424521&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=mC5hmGUGeOKxc4QaMGI1jg&m=Yr1pTBoJ0w6AltcGgSMOMeGqEkDweuMDmgNCpRp7axg&s=ciGA8mioruFG0pCn80NabkODCSO27kFk7hlJXXXawEA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AHDsVNe-5F2XA1PSQwpKYbRRBl0gAB4k-5Fhks5sSMLugaJpZM4OkMkv&d=DwMCaQ&c=clK7kQUTWtAVEOVIgvi0NU5BOUHhpN0H8p7CSfnc_gI&r=mC5hmGUGeOKxc4QaMGI1jg&m=Yr1pTBoJ0w6AltcGgSMOMeGqEkDweuMDmgNCpRp7axg&s=op2uta-sicwVkykKyLirnwSm-oD1KE6865u3m3pBYKQ&e=>
> .
>



-- 
Chao Deng
Graduate Student for Computational Biology Program
Department of Biological Science,
University of Southern California, Los Angeles, CA, U.S.
